# Generated by Django 4.2 on 2023-09-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0002_remove_products_id_alter_products_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsSpecs',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('magnesium_content', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('zinc_content', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('moly_content', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('TBN_content', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('nitrogen_content', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('phosphorus_content', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('sulfur_content', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('boron_content', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
    ]
