# Generated by Django 4.2 on 2023-09-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0003_productsspecs'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsspecs',
            name='calcium_content',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
