# Generated by Django 4.2 on 2023-09-11 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0004_productsspecs_calcium_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='raw_materials_percentage',
            field=models.CharField(default='', max_length=255),
        ),
    ]
