# Generated by Django 4.2 on 2023-09-11 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0005_products_raw_materials_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('name', models.CharField(max_length=22, primary_key=True, serialize=False)),
                ('price_per_kg', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('pdf_blob', models.BinaryField()),
            ],
        ),
    ]
