# Generated by Django 4.2 on 2023-09-11 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0006_sales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='pdf_blob',
        ),
    ]
