# Generated by Django 4.2 on 2023-09-23 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0007_remove_sales_pdf_blob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='weights',
            field=models.CharField(default='', max_length=255),
        ),
    ]
