# Generated by Django 4.2 on 2023-09-24 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0008_alter_products_weights'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='weights',
            new_name='fixed_percentages',
        ),
    ]
