# Generated by Django 4.2 on 2023-07-09 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RawProducts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawproduct',
            name='fcode',
            field=models.CharField(default='N.A', max_length=20),
        ),
    ]
