# Generated by Django 4.2 on 2023-08-21 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RawProducts', '0002_rawproduct_fcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawproduct',
            name='calcium_content',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='rawproduct',
            name='magnesium_content',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='rawproduct',
            name='moly_content',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='rawproduct',
            name='nitrogen_content',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='rawproduct',
            name='zinc_content',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
