# Generated by Django 4.2 on 2023-09-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RawProducts', '0003_rawproduct_calcium_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawproduct',
            name='TBN_content',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='rawproduct',
            name='boron_content',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='rawproduct',
            name='phosphorus_content',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='rawproduct',
            name='sulphur_content',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
