# Generated by Django 4.2 on 2023-09-08 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RawProducts', '0004_rawproduct_tbn_content_rawproduct_boron_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rawproduct',
            old_name='sulphur_content',
            new_name='sulfur_content',
        ),
    ]
