# Generated by Django 4.2 on 2023-09-11 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RawProducts', '0005_rename_sulphur_content_rawproduct_sulfur_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalRawProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('final_calcium_content', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('final_magnesium_content', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('final_zinc_content', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('final_moly_content', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('final_TBN_content', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('final_nitrogen_content', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('final_phosphorus_content', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('final_sulfur_content', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('final_boron_content', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('final_quantity', models.IntegerField()),
                ('final_fcode', models.CharField(default='N.A', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='rawproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
