# Generated by Django 4.2 on 2023-09-11 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RawProducts', '0006_finalrawproduct_rawproduct_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalrawproduct',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
