# Generated by Django 4.2 on 2023-09-23 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RawProducts', '0007_finalrawproduct_final_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempRawProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('temp_calcium_content', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('temp_magnesium_content', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('temp_zinc_content', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('temp_moly_content', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('temp_TBN_content', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('temp_nitrogen_content', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('temp_phosphorus_content', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('temp_sulfur_content', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('temp_boron_content', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('temp_quantity', models.IntegerField()),
                ('temp_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('temp_fcode', models.CharField(default='N.A', max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='FinalRawProduct',
        ),
    ]
